const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const shots = path.join(root, 'docs/equipe/filipe/prototipo/telas');
const results = [];
const errors = [];
(async () => {
  fs.mkdirSync(shots, { recursive: true });
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}, deviceScaleFactor:1});
  page.on('pageerror', e => errors.push(e.message));
  const capture = async name => { await page.screenshot({path:path.join(shots, name+'.png'),fullPage:true,caret:'initial',animations:'disabled'}); };
  const nav = label => page.getByRole('navigation').getByRole('button',{name:label,exact:true}).click();
  const record = (id, task) => { results.push({id, task, result:'Aprovado'}); console.log(id, task); };
  try {
    await page.goto('http://127.0.0.1:3018');
    await page.getByRole('heading',{name:'Acessar o protótipo'}).waitFor();
    await capture('01-acesso');
    await page.getByLabel('Senha fictícia',{exact:true}).fill('teste1234');
    await page.getByRole('button',{name:'Entrar no modo acadêmico'}).click();
    await page.getByRole('heading',{name:'Visão geral',exact:true}).waitFor();
    record('UI01','Login fictício e abertura da visão geral');
    await capture('02-visao-geral');
    await nav('Mapa');
    await page.getByRole('button',{name:'Território Alfa',exact:true}).focus();
    await page.keyboard.press('Enter');
    assert.match(await page.locator('.map-inspector').innerText(),/Alfa/);
    await capture('03-mapa');
    record('UI02','Seleção territorial no mapa');
    await nav('Territórios'); await capture('04-territorios');
    await nav('Pontos de interesse'); await capture('05-pontos');
    await page.getByRole('button',{name:'Planejar visita',exact:true}).first().click();
    assert.equal(await page.getByLabel('Ponto fictício',{exact:true}).inputValue(),'p01');
    await page.getByLabel('Prioridade',{exact:true}).selectOption('high');
    await page.getByLabel('Data da simulação').fill('2026-10-04');
    await page.getByRole('button',{name:'Salvar visita simulada'}).click();
    await page.getByRole('status').filter({hasText:'salva nesta sessão'}).waitFor();
    assert.equal(await page.locator('.visit-card').count(),4);
    record('UI03','Ponto propagado à visita, prioridade e confirmação visual');
    await page.getByRole('button',{name:'Salvar visita simulada'}).click();
    assert.equal(await page.locator('.visit-card').count(),4);
    assert.match(await page.getByRole('status').innerText(),/Já existe/);
    record('UI04','Prevenção de visita duplicada');
    // Restore the successful feedback with a distinct date for a useful screenshot.
    await page.getByLabel('Data da simulação').fill('2026-10-05');
    await page.getByRole('button',{name:'Salvar visita simulada'}).click();
    await capture('07-visitas');
    await page.getByRole('button',{name:'Marcar visita como concluída'}).last().click();
    assert.match(await page.locator('.visit-card').last().innerText(),/Concluída/);
    record('UI05','Conclusão de visita no estado local');
    await nav('Representantes'); await capture('06-representantes');
    await nav('Comparar rotas');
    await page.getByRole('button',{name:'Gerar sugestão'}).click();
    assert.match(await page.locator('.route-card').last().innerText(),/80 km/);
    await page.getByRole('button',{name:'Descer parada 2',exact:true}).click();
    assert.match(await page.locator('.route-card').last().innerText(),/118 km/);
    record('UI06','Geração e reordenação com recálculo de distância');
    await capture('08-rotas');
    await nav('Cobertura e duplicidades'); await capture('09-cobertura');
    await nav('Indicadores');
    assert.match(await page.locator('.method-grid').innerText(),/pré-definida/);
    await capture('10-indicadores');
    record('UI07','Cobertura, duplicidades e explicação dos indicadores');
    await nav('Acessos do Gestão'); await capture('11-permissoes');
    await page.locator('.role-simulator select').selectOption('observation');
    assert.equal(await page.getByRole('button',{name:'Acessos do Gestão',exact:true}).count(),0);
    await nav('Planejar visitas');
    assert.equal(await page.getByRole('button',{name:'Salvar visita simulada'}).isDisabled(),true);
    record('UI08','Perfil de observação sem escrita e sem matriz de acesso');
    await page.locator('.role-simulator select').selectOption('representation');
    assert.equal(await page.getByRole('button',{name:'Indicadores',exact:true}).count(),0);
    record('UI09','Permissões originais de representação preservadas');
    await page.locator('.role-simulator select').selectOption('coordination');
    await page.reload(); await page.getByRole('heading',{name:'Visão geral',exact:true}).waitFor();
    await nav('Planejar visitas');
    assert.equal(await page.locator('.visit-card').count(),3);
    assert.equal(await page.getByLabel('Ponto fictício',{exact:true}).inputValue(),'');
    record('UI10','Recarregamento restaura fixtures e exige seleção explícita');
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
    await nav('Mapa');
    assert.equal(await page.getByRole('heading',{name:'Mapa e municípios',exact:true}).isVisible(),true);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth),false);
    await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= 0);
    await capture('12-mobile');
    record('UI11','Navegação móvel a 390 px sem transbordamento horizontal');
    assert.deepEqual(errors,[]);
    record('UI12','Nenhum erro JavaScript durante o roteiro');
  } finally {
    fs.writeFileSync(path.join(root,'docs/equipe/filipe/testes/ui-results.json'),JSON.stringify({date:new Date().toISOString().slice(0,10),viewport:'1440x1000 e 390x844',results,errors},null,2));
    await browser.close();
  }
})().catch(e=>{console.error(e);process.exitCode=1});
